
spring :
  datasource:
    url: "jdbc:mysql://localhost:3308/GoodsExchange"
    username: root
    password : 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
